name: Android CI - Build & Upload APK

on:
  push:
    branches:
      - main
  
  pull_request:
    
jobs:
  build: 
    name: Build & Upload APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Set up JDK (Java for Android build)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 17

      
      # Step 3: Grant execute permission for Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Build debug APK (ensures app compiles successfully)
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 5: Upload the APK as a  Github artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # # Optional: Also upload logs or reports
      # - name: Upload build reports (optional)
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with: 
      #     name: build-reports
      #     path: app/build/reports